[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {PATH = ":path", VITE_API_BASE_URL = ":cdn_path"}
  [redirects.headers]
    X-Redirect = "false"