[[redirects]]
  from = "/api/*"
  to = "https://axv.0f8.myftpupload.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://medinaenvironmental.netlify.app/*"
  to = "https:///www.medinaenvironmentalcompany.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"